name: george_flutter_radcom_weather
description: Flutter Radcom weather

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  url_launcher: ^6.0.20
  google_fonts: ^2.3.1
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true